services:
  app:
    build:
      context: ./frontend
    container_name: frontend
    env_file:
      - .env.frontend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"
      - app_node_modules:/app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - .env.backend
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/app"

volumes:
  app_node_modules:
